routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

//Route::auth();

// Admin middleware
Route::group(['middleware'=>'admin', 'as' => 'admin.'], function(){

	Route::get('/admin', function(){
		return view('admin.index');
	});
	Route::resource('/admin/users', 'AdminUsersController');
	//Route::get('admin/media/upload',['as'=>'admin.media.upload', 'uses'=>'AdminMediasController@store']);
	
});

// Business Owner middleware
Route::group(['middleware'=>'bowner', 'as' => 'bowner.'], function(){

	// Homepage
	Route::get('/bowner', function(){
		return view('bowner.index');
	});

	// Human Resource route
	Route::resource('/bowner/humans', 'BownerHumansController');

	// Salary route
	Route::post('/bowner/salaries', 'BownerSalariesController@index');
	Route::post('/bowner/salaries/store', [
		'uses' => 'BownerSalariesController@store',
		'as' => 'salaries.store' ]);
	Route::resource('/bowner/salaries', 'BownerSalariesController', ['except'=>['store']]);

	// Leave route
	Route::resource('/bowner/leaves', 'LeavesController');

	// Chart route
	Route::get('bowner/chart', [
		'uses' => 'ChartController@index',
		'as' =>'chart.index'
	]);

	// Customer route
	Route::resource('bowner/customer', 'CustomerController', ['except'=>['store']]);

	// Order route
	Route::get('order_delete/{order_id}',[
		'uses' => 'OrderController@destroy',
		'as' => 'orders.destroy',
	]);
	Route::get('order_complete/{order_id}',[
		'uses' => 'OrderController@complete',
		'as' =>'orders.complete',
	]);
	Route::get('order_submit/{order_id}', [
		'uses' => 'OrderController@submit',
		'as' => 'orders.submit',
	]);
	Route::get('order_deliver/{order_id}', [
		'uses' => 'OrderController@deliver',
		'as' => 'orders.deliver',
	]);

	/*
	Route::get('bowner/inventories/material/purchase', [
		'uses' => 'MaterialPurchaseController@index',
		'as' => 'purchase.index'
	]);
	Route::get('bowner/inventories/material/purchase/create', [
		'uses' => 'MaterialPurchaseController@create',
		'as' => 'purchase.create'
	]);
	Route::post('bowner/inventories/material/purchase/store', [
		'uses' => 'MaterialPurchaseController@store',
		'as' => 'purchase.store'
	]);
	*/
});

// Order route
/*
Route::group(['middleware'=>'auth'], function(){
	Route::resource('/orders', 'OrderController', ['except'=>['destroy']]);
	Route::get('/delete_order/{order_id}',[
		'uses' => 'OrderController@destroy',
		'as' => 'orders.destroy',
	]);
	Route::get('/complete_order/{order_id}',[
		'uses' => 'OrderController@complete',
		'as' =>'orders.complete',
	]);
*/
// BusinessOwner_Manager middleware
Route::group(['middleware' => 'bowner_manager', 'as' => 'bowner.'], function() {

	Route::get('manager', function(){
		return view('bowner.index');
	});

	// Production route
	Route::resource('bowner/production', 'ProductionController');
	Route::get('bowner/complete_production/{o_qty}/{p_id}/{p_qty}',[
		'uses' => 'ProductionController@complete',
		'as' =>'production.complete',
	]);

	// Inventories route
	Route::resource('bowner/inventories', 'InventoryController');

	Route::get('bowner/inventories/product/edit/{product_id}', [
		'uses' => 'InventoryController@editProduct',
		'as' => 'inventories.product.edit'
	]);
	Route::get('bowner/inventories/material/edit/{material_id}', [
		'uses' => 'InventoryController@editMaterial',
		'as' => 'inventories.material.edit'
	]);
	Route::patch('bowner/inventories/product/update/{product_id}', [
		'uses' => 'InventoryController@updateProduct',
		'as' => 'inventories.product.update'
	]);
	Route::patch('bowner/inventories/material/update/{material_id}', [
		'uses' => 'InventoryController@updateMaterial',
		'as' => 'inventories.material.update'
	]);

	// Purchasing route
	Route::resource('bowner/inventories/material/purchase', 'MaterialPurchaseController', ['except'=>'destroy']);
	Route::get('bowner/inventories/material/purchase/delete/{purchase_id}', [
		'uses' => 'MaterialPurchaseController@destroy',
		'as' => 'purchase.destroy'
	]);
	Route::get('bowner/inventories/material/purchase/complete/{purchase_id}', [
		'uses' => 'MaterialPurchaseController@complete',
		'as' => 'purchase.complete'
	]);

	// Supplier route
	Route::resource('bowner/supplier', 'SupplierController');

});

// Employee_BusinessOwner middleware
Route::group(['middleware' => 'bowner_employee'], function() {

	// Order route
	Route::resource('orders', 'OrderController', ['except'=>['destroy']]);

	// Customer creation route
	Route::get('customer/create', 'CustomerController@create');
	Route::post('customer', 'CustomerController@store')->name('customer');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Purchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    //
    public function material()
    {
    	return $this->belongsTo('App\Material');
    }

    public function supplier()
    {
    	return $this->belongsTo('App\Supplier');
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Session;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Material;
use App\Product;
use App\Supplier;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $products = Product::all();
        $materials = Material::all();
        return view('bowner.inventories.index', compact('products', 'materials', 'purchases'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function editProduct($id)
    {
        //
        $product = Product::findOrFail($id);
        return view('bowner.inventories.product.edit', compact('product'));
    }

    public function editMaterial($id)
    {
        //
        $material = Material::findOrFail($id);
        return view('bowner.inventories.material.edit', compact('material'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    public function updateProduct(Request $request, $id)
    {
        //
        $product = Product::findOrFail($id);
        $p_qty = $product->quantity = $request->quantity;

        // If 'hod' so no 'extra'
        if ($request->extra != null) {
            $extra = $product->extra = $request->extra;

            if ($extra >= $product->unit->equi) {
                $product->quantity = $p_qty + floor($extra / $product->unit->equi);
                $product->extra = $extra % $product->unit->equi;
            }
        }

        $product->save();

        Session::flash('updated_message', 'The product available quantity has been updated');

        return redirect('/bowner/inventories');
    }

    public function updateMaterial(Request $request, $id)
    {
        //
        $material = Material::findOrFail($id);
        $material->quantity = $request->quantity;
        $material->save();

        Session::flash('updated_message', 'The material available quantity has been updated');

        return redirect('/bowner/inventories');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/bowner/inventories/purchase/create.blade.php
@extends('layouts.bowner')

@section('content')

	<h1>Purchase Material</h1>

	{!! Form::open(['method'=>'POST', 'action'=>'MaterialPurchaseController@store', 'class'=>'form-group']) !!}
	<div class="row">
		<div class="form-group col-sm-6">
			{!! Form::label('material_id', 'Material (*):') !!}
			<select name="material_id" id="material_id" class="form-control" required>
				<option value="" selected>Choose Material</option>
				@foreach($materials as $material)
					<option value="{{ $material->id }}">{{ $material->name .' ('.$material->unit->name .')'}}</option>
				@endforeach
			</select>
		</div>	

		<div class="form-group col-sm-6">
			{!! Form::label('supplier_id', 'Supplier (*):') !!}
			{!! Form::select('supplier_id', [''=>'Choose Supplier'] + $suppliers, null, ['class'=>'form-control', 'required']) !!}
		</div>
	</div>	
	
	<div class="row">
		<div class="form-group col-sm-6">
			{!! Form::label('quantity', 'Purchase Quantity (*):') !!}
			{!! Form::number('quantity', null, ['class'=>'form-control', 'min'=>1, 'required']) !!}
		</div>
	</div>

	<div class="row">
		<div class="form-group col-sm-6">
			{!! Form::submit('Purchase Material', ['class'=>'btn btn-primary']) !!}
			<a class="btn btn-warning" href="{{URL('/bowner/inventories/material/purchase')}}">Cancel</a>
		</div>
	</div>

	{!! Form::close() !!}

@stop

resources/views/bowner/inventories/purchase/edit.blade.php
@extends('layouts.bowner')

@section('content')

	<h1>Edit Purchasing</h1>

	{!! Form::model($purchase, ['method'=>'PATCH', 'action'=>['MaterialPurchaseController@update', $purchase->id], 'class'=>'form-group']) !!}
	<div class="row">
		<div class="form-group col-sm-6">
			{!! Form::label('material_id', 'Material (*):') !!}
			<select name="material_id" id="material_id" class="form-control" required>
				@foreach($materials as $material)
					<option value="{{ $material->id }}" {{ $material->id == $purchase->material_id ? 'selected' : '' }}>{{ $material->name .' ('.$material->unit->name .')'}}</option>
				@endforeach
			</select>
		</div>	

		<div class="form-group col-sm-6">
			{!! Form::label('supplier_id', 'Supplier (*):') !!}
			{!! Form::select('supplier_id', [''=>'Choose Supplier'] + $suppliers, null, ['class'=>'form-control', 'required']) !!}
		</div>	

		<div class="form-group col-sm-6">
			{!! Form::label('quantity', 'Purchase Quantity (*):') !!}
			{!! Form::number('quantity', null, ['class'=>'form-control', 'min'=>1, 'required']) !!}
		</div>
	</div>

	<div class="row">
		<div class="form-group col-sm-6">
			{!! Form::submit('Save', ['class'=>'btn btn-primary']) !!}
			<a class="btn btn-warning" href="{{URL('/bowner/inventories/material/purchase')}}">Cancel</a>
		</div>
	</div>

	{!! Form::close() !!}

@stop

resources/views/bowner/inventories/purchase/index.blade.php
@extends('layouts.bowner')

@section('content')

	@include('includes.message')

	<h1>All Purchases</h1>
	<div class="row">
		<div class="table-responsive">
			<table class="table table-bordered table-striped">
			    <thead>
			      <tr>
			        <th>Id</th>
			        <th>Actions</th>
			        <th>Product</th>
			        <th>Cost</th>
			        <th>UOM</th>
			        <th>Quantity</th>
			        <th>Supplier</th>
			        <th>Total Cost</th>
			        <th>Status</th>
			        <th>Date</th>
			      </tr>
			    </thead>
			    <tbody>
					@foreach($purchases as $purchase)
					  <tr>
						<td>{{$purchase->id}}</td>
						<td>
							<div style="display: inline-flex;">
							<!-- Edit button -->
						@if ($purchase->status == 0)
							<a class="btn btn-xs btn-primary" data-toggle="tooltip" data-placement="left" title="edit purchase" href="{{route('bowner.purchase.edit', $purchase->id)}}"><span class="glyphicon glyphicon-pencil"></span></a>
						@else 
							<a href="#" class="btn btn-xs btn-primary disabled"><span class="glyphicon glyphicon-ok"></span></a>
						@endif
							<!-- Delete button -->
							<a class="btn btn-xs btn-danger" data-toggle="tooltip" data-placement="top" title="delete purchase" href="{{route('bowner.purchase.destroy', $purchase->id)}}"><span class="glyphicon glyphicon-remove"></span></a>
						@if ($purchase->status == 0)
							<!-- Complete button -->
							<a class="btn btn-xs btn-default" data-toggle="tooltip" data-placement="right" title="complete purchase" href="{{route('bowner.purchase.complete', $purchase->id)}}"><span class="glyphicon glyphicon-ok"></span></a>
						@else
							<!-- Undo button -->
							<!--
							<a class="btn btn-xs btn-default" data-toggle="tooltip" data-placement="right" title="undo completing purchase" href="{{route('bowner.purchase.complete', $purchase->id)}}"><span class="glyphicon glyphicon-repeat"></span></a>
							-->
						@endif
							</div>
						</td>
						<td>{{$purchase->material->name}}</td>
						<td>{{$purchase->material->cost}}</td>
						<td>{{$purchase->material->unit->name}}</td>
						<td>{{$purchase->quantity}}</td>
						<td>{{$purchase->supplier->name}}</td>
						<td>{{number_format($purchase->quantity * $purchase->material->cost,2,'.','')}}</td>
						@if ($purchase->status == 1)
							<td class="success">Completed <span class="glyphicon glyphicon-ok text-success"></span></td>
						@else 
							<td>Pending</td>
						@endif	
						<td>{{date("d-m-Y", strtotime($purchase->updated_at))}}</td>
					  </tr>
					@endforeach
			    </tbody>
		  	</table>
	  	</div><!-- /.table-responsive -->
	</div><!-- /.row -->
	<!-- / View Purchasing Material -->
		
	<!-- Pagination -->
  	<div class="row">
  		<div class="text-center">
  			{{ $purchases->render() }}
  		</div>
  	</div>
	
	<!-- Purchase button -->
	<div class="container">
	  	<a class="btn btn-info" href="{{route('bowner.purchase.create')}}">Purchase Material</a>
	</div>

@stop