routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

//Route::auth();

// Admin middleware
Route::group(['middleware'=>'admin', 'as' => 'admin.'], function(){

	Route::get('/admin', function(){
		return view('admin.index');
	});
	Route::resource('/admin/users', 'AdminUsersController');
	//Route::get('admin/media/upload',['as'=>'admin.media.upload', 'uses'=>'AdminMediasController@store']);
	
});

// Business Owner middleware
Route::group(['middleware'=>'bowner', 'as' => 'bowner.'], function(){

	// Homepage
	Route::get('/bowner', function(){
		return view('bowner.index');
	});

	// Human Resource route
	Route::resource('/bowner/humans', 'BownerHumansController');

	// Salary route
	Route::post('/bowner/salaries', 'BownerSalariesController@index');
	Route::post('/bowner/salaries/store', [
		'uses' => 'BownerSalariesController@store',
		'as' => 'salaries.store' ]);
	Route::resource('/bowner/salaries', 'BownerSalariesController', ['except'=>['store']]);

	// Leave route
	Route::resource('/bowner/leaves', 'LeavesController');

	// Chart route
	Route::get('bowner/chart', [
		'uses' => 'ChartController@index',
		'as' =>'chart.index'
	]);

	// Customer route
	Route::resource('bowner/customer', 'CustomerController', ['except'=>['store']]);

	// Order route
	Route::get('order_delete/{order_id}',[
		'uses' => 'OrderController@destroy',
		'as' => 'orders.destroy',
	]);
	Route::get('order_complete/{order_id}',[
		'uses' => 'OrderController@complete',
		'as' =>'orders.complete',
	]);
	Route::get('order_submit/{order_id}', [
		'uses' => 'OrderController@submit',
		'as' => 'orders.submit',
	]);
	Route::get('order_deliver/{order_id}', [
		'uses' => 'OrderController@deliver',
		'as' => 'orders.deliver',
	]);

	/*
	Route::get('bowner/inventories/material/purchase', [
		'uses' => 'MaterialPurchaseController@index',
		'as' => 'purchase.index'
	]);
	Route::get('bowner/inventories/material/purchase/create', [
		'uses' => 'MaterialPurchaseController@create',
		'as' => 'purchase.create'
	]);
	Route::post('bowner/inventories/material/purchase/store', [
		'uses' => 'MaterialPurchaseController@store',
		'as' => 'purchase.store'
	]);
	*/
});

// Order route
/*
Route::group(['middleware'=>'auth'], function(){
	Route::resource('/orders', 'OrderController', ['except'=>['destroy']]);
	Route::get('/delete_order/{order_id}',[
		'uses' => 'OrderController@destroy',
		'as' => 'orders.destroy',
	]);
	Route::get('/complete_order/{order_id}',[
		'uses' => 'OrderController@complete',
		'as' =>'orders.complete',
	]);
*/
// BusinessOwner_Manager middleware
Route::group(['middleware' => 'bowner_manager', 'as' => 'bowner.'], function() {

	Route::get('manager', function(){
		return view('bowner.index');
	});

	// Production route
	Route::resource('bowner/production', 'ProductionController');
	Route::get('bowner/complete_production/{o_qty}/{p_id}/{p_qty}',[
		'uses' => 'ProductionController@complete',
		'as' =>'production.complete',
	]);

	// Inventories route
	Route::resource('bowner/inventories', 'InventoryController');

	Route::get('bowner/inventories/product/edit/{product_id}', [
		'uses' => 'InventoryController@editProduct',
		'as' => 'inventories.product.edit'
	]);
	Route::get('bowner/inventories/material/edit/{material_id}', [
		'uses' => 'InventoryController@editMaterial',
		'as' => 'inventories.material.edit'
	]);
	Route::patch('bowner/inventories/product/update/{product_id}', [
		'uses' => 'InventoryController@updateProduct',
		'as' => 'inventories.product.update'
	]);
	Route::patch('bowner/inventories/material/update/{material_id}', [
		'uses' => 'InventoryController@updateMaterial',
		'as' => 'inventories.material.update'
	]);

	// Purchasing route
	Route::resource('bowner/inventories/material/purchase', 'MaterialPurchaseController', ['except'=>'destroy']);
	Route::get('bowner/inventories/material/purchase/delete/{purchase_id}', [
		'uses' => 'MaterialPurchaseController@destroy',
		'as' => 'purchase.destroy'
	]);
	Route::get('bowner/inventories/material/purchase/complete/{purchase_id}', [
		'uses' => 'MaterialPurchaseController@complete',
		'as' => 'purchase.complete'
	]);

	// Supplier route
	Route::resource('bowner/supplier', 'SupplierController');

});

// Employee_BusinessOwner middleware
Route::group(['middleware' => 'bowner_employee'], function() {

	// Order route
	Route::resource('orders', 'OrderController', ['except'=>['destroy']]);

	// Customer creation route
	Route::get('customer/create', 'CustomerController@create');
	Route::post('customer', 'CustomerController@store')->name('customer');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

app/production.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class production extends Model
{
    //
}

app/Http/Controllers/ProductionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Session;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\OrderDetail;
use App\Production;
use App\Material;
use App\Product;
use App\Order;

class ProductionController extends Controller
{
    public function index()
    {
    	$orders = Order::where('deliver', 0)->where('submit', 1)->paginate(10);
        $products = Product::pluck('quantity','id');
        foreach ($products as $key => $value) {
            $flag[$key] = 0;
        }

    	return view('bowner.production.index', compact('orders', 'products', 'flag'));
    }

    public function show($id)
    {
    	$order = Order::findOrFail($id);

    	return view('bowner.production.print', compact('order'));
    }

    public function complete($detail_qty, $id, $p_qty)
    {
        $product = Product::findOrFail($id);
        $material = Material::findOrFail($product->material_id);
        $o_qty = $detail_qty;
        $cur_prod_qty = $product->quantity;
        $p_extra = $product->extra;
        $m_qty = $material->quantity;
        $p_unit_equi = $product->unit->equi;
        $m_unit_equi = $material->unit->equi;

        // update product and material quantity
        if ($p_qty < 0) { $p_qty = 0; }
        $required_p_qty = $o_qty - $p_qty;
        $required_m_qty = intval(ceil(($required_p_qty * $p_unit_equi) / $m_unit_equi ));
        $extra_qty = $p_extra + $required_m_qty * $m_unit_equi - $required_p_qty * $p_unit_equi;
        
        // Include extra calculation
        $check_extra = $required_p_qty * $p_unit_equi % $m_unit_equi;

        // Check if extra is enough for 1 product qty
        if (($check_extra != 0) && ($check_extra <= $p_extra)) {
            $required_m_qty = $required_m_qty - 1;
            $extra_qty = $p_extra - $check_extra; 
        }

        $product->quantity = $cur_prod_qty + $required_p_qty;
        $product->extra = $extra_qty;

        if ($extra_qty > $p_unit_equi) {
            $product->quantity += intval(floor($extra_qty / $p_unit_equi));
            $product->extra = $extra_qty % $p_unit_equi;
        }

        $material->quantity = $m_qty - $required_m_qty; // remain material qty

        $product->save(); 
        $material->save();

        Session::flash('updated_message', 'The production has been updated');

        return redirect()->back();
    }

}

resources/views/bowner/production/index.blade.php
@extends('layouts.bowner')

@section('content')

	@include('includes.message')

	<h1>Production</h1>

	<div class="btn btn-primary" onClick="window.print()"><span class="glyphicon glyphicon-print"></span> Print This Page</div><br><br>

	<!-- Start .table-responsive -->
	<div class="table-responsive">
		<table class="table table-responsive table-bordered table-striped">
			<thead>
				<tr>
					<th>Order Id</th>
					<th>Product</th>
					<th>UOM</th>
					<th>Order Qty</th>
					<th>Inventory Qty</th>
					<th>(Extra)</th>
					<th>Material Qty</th>
					<th>Status</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
			@foreach ($orders as $order)
				@php 
					$i = 0; // count items in an order 
					$orderFilled[$order->id] = 1;
				@endphp
				<tr>
					<td rowspan="{{ $count = count($order->orderdetail()->get()) }}">{{ $order->id }}</td>
				@foreach ($order->orderdetail()->get() as $detail)
					@php 
						$i++;
					@endphp
						<td>{{ $detail->product->name }}</td>
						<td>{{ $detail->product->unit->name }}</td>
						<td>{{ $detail->quantity }}</td>
						<td>{{ $products[$detail->product_id] }} (x <i>{{ $detail->product->unit->equi }}</i>)</td>
						<td><i>{{ $detail->product->extra }}<i></td>
						<td>{{ $detail->product->material->quantity }} (x <i>{{ $detail->product->material->unit->equi }}</i>)</td>
						@if (($o_qty = $detail->quantity) <= $products[$detail->product_id])
							@php
								$flag[$detail->product_id] = 0
							@endphp
							<!-- Filled status -->
							<td class="success">Filled &nbsp;
							{{-- Appear print after done checking all items of the order --}}
							@if (($i == $count) && ($orderFilled[$order->id] == 1))
								<a class="btn btn-xs btn-success pull-right" href="{{route('bowner.production.show', $order->id)}}" target="_blank"><span class="glyphicon glyphicon-print" data-toggle="tooltip" data-placement="top" title="print"></span></a>
							@endif
							</td>
						@elseif ((($m_qty = $detail->product->material->quantity) <= 0) || ((($o_qty - $products[$detail->product_id]) * $detail->product->unit->equi) > ($m_qty * $detail->product->material->unit->equi)))
							<!-- Lack Material status -->
							<td class="warning">Lack Material</td>
							@php
								$orderFilled[$order->id] = 0;
							@endphp
						@else
							<!-- Under Production status -->
							<td>Ready for Production 
							@if ($flag[$detail->product_id] == 0)
								<a class="btn btn-xs btn-default pull-right" data-toggle="tooltip" data-placement="top" title="complete production" href="{{ route('bowner.production.complete', [$detail->quantity, $detail->product_id, $products[$detail->product_id]]) }}"><span class="glyphicon glyphicon-ok"></span></a>
								@php 
									$flag[$detail->product_id] = 1;
									$orderFilled[$order->id] = 0;
								@endphp
							@endif
							</td>
						@endif
						<td>{{ date("d-m-Y", strtotime($detail->updated_at)) }}</td>
					</tr>
					@php 
						$products[$detail->product_id] -= $detail->quantity 
					@endphp
				@endforeach
			@endforeach
			</tbody>
		</table>
	</div>
	<!-- / .table-responsive -->

	<!-- Pagination -->
  	<div class="row">
  		<div class="text-center">
  			{{ $orders->render() }}
  		</div>
  	</div>

@stop

@section('scripts')
<script>
</script>
@stop

resources/views/bowner/production/print.blade.php
@extends('layouts.print')

@section('content')
    <h2 class="text-center text-primary">Product Delivery</h2>
    <hr>
    <h4>Order ID: <b>{{ $order->id }}</b></h4>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Product</th>
                        <th>UOM</th>
                        <th>Quantity</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                @php
                    $i = 1;
                @endphp
                @foreach ($order->orderdetail()->get() as $detail)
                <tr>
                    <td>{{ $i++ }}</td>
                    <td>{{ $detail->product->name }}</td>
                    <td>{{ $detail->product->unit->name }}</td>
                    <td>{{ $detail->quantity }}</td>
                    <td>{{ date("d-m-Y") }}</td>
                </tr>
                @endforeach
            </tbody>
            </table>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-3">
            <h4>Inventory Manager Signature</h4>
            <br><br><br><br><br>
        </div>
        <div class="col-md-offset-6 col-md-3">
            <h4>Business Owner Signature</h4>
        </div>
    </div>
</div>
@stop